"""
Placeholder tile art for a deck.

A deck's *config* (palette + geometry + manifest) is committed under
`decks/configs/<name>/`; its *tiles* are not. This module regenerates a
runnable set of placeholder tiles so the pipeline builds before any real art
exists, and so a new deck can be bootstrapped from code.

Two kinds of source live here, and both stay in code rather than as committed
binary artifacts:

  - `corner`, `edge`, `roundel` are generated procedurally.
  - the five pips (`cups`, `wands`, `swords`, `pentacles`, `rose`) are the nicer
    hand-authored tiles, kept as ASCII string constants and parsed on demand.

`seed_deck(dest_root)` writes the border/cartouche tiles as indexed PNG and the
pips as ASCII `.txt` — deliberately mixed, to exercise `tileio.read_any`.
"""
from __future__ import annotations
from pathlib import Path
import numpy as np

from arcana.palette import T, LINE, PAPER, DARK, MID, LIGHT
from arcana.compose import profile_strip
from arcana.elements import write_tile, write_authoring_palette
from arcana.tileio import from_ascii, write_ascii


# ---------------------------------------------------------------- procedural
def corner(C: int = 16) -> np.ndarray:
    c = profile_strip(C, C)
    c[:, 0:1] = LINE; c[:, 1:2] = MID; c[:, 2:3] = LIGHT
    c[5:, 5:7] = DARK
    for r, k in ((8, 8), (9, 11), (11, 9), (12, 12), (10, 14), (14, 10)):
        c[r:r + 2, k:k + 2] = DARK
    return c


def edge(C: int = 16, E: int = 8) -> np.ndarray:
    e = profile_strip(C, E)
    e[8:10, 1:7] = DARK; e[10:12, 3:5] = DARK
    return e


def roundel(S: int = 24) -> np.ndarray:
    c = np.zeros((S, S), np.uint8)
    yy, xx = np.mgrid[0:S, 0:S]
    r = np.hypot(xx - (S - 1) / 2, yy - (S - 1) / 2)
    c[r <= S / 2 - 0.4] = LINE
    c[r <= S / 2 - 1.2] = MID
    c[r <= S / 2 - 2.6] = PAPER
    return c


# ---------------------------------------------------------------- pips (ASCII)
# Hand-authored, kept in code. Glyphs: . transparent  @ line  ' paper
# % dark  + mid  - light. Each is 16x16 and self-symmetric about x=7.5 so odd
# pip counts stay symmetric on the lattice.
PIPS_ASCII = {
    "cups": """
................
................
...@@@@@@@@@@...
...+----+++++...
...+----+++++...
...++++++++++...
...++++++++++...
...++++++++++...
.....%%%%%%.....
.......%%.......
.......%%.......
....%%%%%%%%....
...@@@@@@@@@@...
................
................
................
""",
    "wands": """
................
......@@@@......
......-++%......
......-++%......
....%%%%%%%%....
......-++%......
......-++%......
....%%%%%%%%....
......-++%......
......-++%......
....%%%%%%%%....
......-++%......
......-++%......
......@@@@......
................
................
""",
    "swords": """
................
.......@@.......
.......-+.......
.......-+.......
.......-+.......
.......-+.......
.......-+.......
.......-+.......
.......-+.......
...%%%%%%%%%%...
...%%%%%%%%%%...
.......++.......
.......++.......
.......++.......
......@@@@......
................
""",
    "pentacles": """
................
.....%%%%%%.....
....%%%++%%%....
...%%--%%--%%...
..%%---%%---%%..
.%%----%%----%%.
.%%%%%%%%%%%%%%.
.%+-%%%--%%%-+%.
.%+--%%--%%--+%.
.%%--%%%%%%--%%.
.%%--%%%%%%--%%.
..%%-%%--%%-%%..
...%%------%%...
....%%%++%%%....
.....%%%%%%.....
................
""",
    "rose": """
................
................
.....%%%%%%.....
...%%+++%++%%...
...%%---%--%%...
..%+-%--%-%-+%..
..%+--%%%%--+%..
..%+--%%%%--+%..
..%%%%%%%%%%%%..
..%+--%%%%--+%..
..%+-%--%-%-+%..
...%%---%--%%...
...%%+++%++%%...
.....%%%%%%.....
................
................
""",
}


def pip(name: str) -> np.ndarray:
    """The 16x16 local-index matrix for a suit pip."""
    return from_ascii(PIPS_ASCII[name])


# ---------------------------------------------------------------- seed
def seed_deck(dest_root: str | Path) -> Path:
    """Write a full set of placeholder tiles (and the authoring palette) under
    dest_root, laid out to match the standard element manifest. Border and
    cartouche are indexed PNG; pips are ASCII .txt."""
    root = Path(dest_root)
    write_authoring_palette(root)
    write_tile(corner(), root / "border/corner.border.png")
    write_tile(edge(), root / "border/edge.border.png")
    write_tile(roundel(), root / "cartouche/roundel.motif.png")
    for name in PIPS_ASCII:
        write_ascii(pip(name), root / f"pips/{name}.motif.txt", name=f"{name}.motif")
    return root
